### ISSUE TITLE
[Feature Request] Configure Colors

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-TerminalMessaging#2]
Yeah, it's me again, on another one of your highly useful plugins :)

Could you eventually add color configuration for the text?  I use a number of different themes on my different printer instances so I can tell instantly at a glance which instance at which I am looking.  Unfortunately, your color combo does not always go well with different themes, which makes it hard to read.  If I could set my own colors for the text(s), it would alleviate this issue.

**Comment by jneilliii** [comment]
I doubt I'll do much with this plugin to be honest. You should submit a Feature Request on the official version (the person I wrote the plugin for).

https://plugins.octoprint.org/plugins/terminalmessaging/
